# the docker-compose setup that uses grunt's built files in dist/
# (closer to what will be running in production)

cockpit:
  image: nginx
  volumes:
    - ./dist/:/usr/share/nginx/html/
    - ./nginx-default-dist.conf:/etc/nginx/conf.d/default.conf:ro
    - ./dist/nginx-dist.conf:/etc/nginx/nginx.conf:ro
    - ./dist/mime.types:/etc/nginx/mime.types:ro
    - ./dist/h5bp/:/etc/nginx/h5bp/
  ports:
    - "8080:80"
  links:
    - musterroll
musterroll:
  image: cloudfleet/blimp-musterroll
  command: node server.js --testing=true
