cockpit:
  build: .
  volumes:
    - ./app/:/usr/share/nginx/html/
    # - ./dist/:/usr/share/nginx/html/
    - ./bower_components/:/usr/share/nginx/html/bower_components/
    - ./.tmp/styles/:/usr/share/nginx/html/styles/
    - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
  ports:
    - "8080:80"
  links:
    - musterroll
musterroll:
  image: cloudfleet/blimp-musterroll
  command: node server.js --testing=true

