cockpit:
  build: .
  volumes:
    - ./public/:/usr/share/nginx/html/
    - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
  ports:
    - "8080:80"
  links:
    - musterroll
musterroll:
  image: cloudfleet/blimp-musterroll

