---
- name: setup owncloud repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /' state=present

- name: get repository key for owncloud
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_14.04/Release.key



- name: install owncloud
  apt: pkg={{ item }} state=present  update_cache=yes
  with_items:
  - owncloud
  - php5-ldap

- name: copy installation file
  copy: src=owncloud.config.php dest=/var/www/owncloud/config/config.php

- name: set owner of installation file
  file: path=/var/www/owncloud/config/config.php owner=www-data

- name: copy database file
  copy: src=blimp_oc.sql dest=/tmp/blimp_oc.sql

- name: restoring database
  sudo: yes
  sudo_user: postgres
  command: psql -d blimp_oc -f /tmp/blimp_oc.sql

